import {
  Motorbike,
  Home,
  ShieldCheck,
  AlertTriangle,
  FileX2,
  DollarSign,
  FileCheck2,
  FileBadge,
} from 'lucide-react';
import { DocumentTypeItem } from './types';

export const DOCUMENT_TYPES_LIST: DocumentTypeItem[] = [
  {
    id: 'contrato_locacao_moto_completo',
    title: 'Contrato de Locação de Moto (Modelo Oficial)',
    category: 'Motos',
    badge: '12 Cláusulas + Vistoria',
    badgeColor: 'bg-[#8B5CF6]/15 text-[#A78BFA] border-[#8B5CF6]/30',
    icon: Motorbike,
    desc: 'Contrato oficial com todas as 12 cláusulas, prazo mínimo de 3 meses, caução, vistoria 360°, franquia de seguro e Anexo I.',
  },
  {
    id: 'recibo_caucao',
    title: 'Recibo de Caução Locatícia',
    category: 'Garantia',
    badge: 'Essencial',
    badgeColor: 'bg-[#F97316]/10 text-[#F97316] border-[#F97316]/20',
    icon: ShieldCheck,
    desc: 'Comprovante oficial de depósito de caução em garantia com regras de restituição, conservação e quitação rescisória.',
  },
  {
    id: 'notificacao_cobranca',
    title: 'Notificação de Cobrança / Atraso',
    category: 'Jurídico',
    badge: 'Cobrança',
    badgeColor: 'bg-[#EF4444]/10 text-[#EF4444] border-[#EF4444]/20',
    icon: AlertTriangle,
    desc: 'Notificação formal com cálculo de multa (2%), juros de mora (1% a.m.), chave PIX e prazo legal de 48h.',
  },
  {
    id: 'termo_rescisao',
    title: 'Termo de Rescisão / Distrato Contratual',
    category: 'Encerramento',
    badge: 'Distrato',
    badgeColor: 'bg-[#8B5CF6]/10 text-[#8B5CF6] border-[#8B5CF6]/20',
    icon: FileX2,
    desc: 'Instrumento de distrato amigável, apuração de contas, desconto de taxa de limpeza/reparos e quitação recíproca.',
  },
  {
    id: 'contrato_kitnet',
    title: 'Contrato de Locação de Kitnet',
    category: 'Kitnets',
    badge: 'Completo',
    badgeColor: 'bg-[#8B5CF6]/10 text-[#8B5CF6] border-[#8B5CF6]/20',
    icon: Home,
    desc: 'Locação residencial completa (19 cláusulas) com água/IPTU inclusos, normas de convivência e caução retida.',
  },
  {
    id: 'recibo_parcela',
    title: 'Recibo de Pagamento de Parcela',
    category: 'Financeiro',
    badge: 'Recibo',
    badgeColor: 'bg-[#9C9CA3]/10 text-[#9C9CA3] border-[#2A2A2E]',
    icon: DollarSign,
    desc: 'Comprovante individual de pagamento de mensalidade com discriminação por extenso, competência e quitação.',
  },
  {
    id: 'termo_entrega_moto',
    title: 'Termo de Entrega & Vistoria da Moto',
    category: 'Motos',
    badge: 'Vistoria',
    badgeColor: 'bg-[#9C9CA3]/10 text-[#9C9CA3] border-[#2A2A2E]',
    icon: FileCheck2,
    desc: 'Laudo de entrega física e vistoria, registro de quilometragem inicial (KM) e checklist de integridade mecânica.',
  },
  {
    id: 'termo_quitacao',
    title: 'Termo de Quitação & Transferência',
    category: 'Motos',
    badge: 'Liberação',
    badgeColor: 'bg-[#10B981]/10 text-[#10B981] border-[#10B981]/20',
    icon: FileBadge,
    desc: 'Declaração formal de quitação integral do veículo e autorização para transferência definitiva de titularidade no DETRAN.',
  },
];
